Update workflows

diff --git a/.github/workflows/test-local-action.yaml b/.github/workflows/test-local-action.yaml
--- a/.github/workflows/test-local-action.yaml
+++ b/.github/workflows/test-local-action.yaml
@@ -48,3 +48,109 @@ jobs:
       - name: Run functional tests
         run: |
           python -m pytest tests/functional
+
+  long-python-version:
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    strategy:
+      max-parallel: 8
+      fail-fast: false
+      matrix:
+        python-version: [ '3.14', '3.13', '3.12', '3.11', '3.10' ]
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Install uv and set the python version
+        uses: astral-sh/setup-uv@v7
+        with:
+          python-version: ${{ matrix.python-version }}
+          activate-environment: true
+
+      - name: Install packages
+        run: |
+          uv pip install pytest
+
+      - name: Install valid package version
+        uses: ./
+        with:
+          package-name: numpy
+          package-version: 2.4
+          python-version: ${{ matrix.python-version }}.0
+
+      - name: Run functional tests
+        run: |
+          python -m pytest tests/functional
+
+
+  without-python-version:
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    strategy:
+      max-parallel: 8
+      fail-fast: false
+      matrix:
+        python-version: [ '3.14', '3.13', '3.12', '3.11', '3.10' ]
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Install uv and set the python version
+        uses: astral-sh/setup-uv@v7
+        with:
+          python-version: ${{ matrix.python-version }}
+          activate-environment: true
+
+      - name: Install packages
+        run: |
+          uv pip install pytest
+
+      - name: Install valid package version
+        uses: ./
+        with:
+          package-name: numpy
+          package-version: 2.4
+
+      - name: Run functional tests
+        run: |
+          python -m pytest tests/functional
+
+
+  incorrect-python-version:
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    strategy:
+      max-parallel: 8
+      fail-fast: false
+      matrix:
+        python-version: [ '3.14', '3.13', '3.12', '3.11', '3.10' ]
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Install uv and set the python version
+        uses: astral-sh/setup-uv@v7
+        with:
+          python-version: ${{ matrix.python-version }}
+          activate-environment: true
+
+      - name: Install valid package version
+        uses: ./
+        id: install-package
+        with:
+          package-name: numpy
+          package-version: 2.4
+          python-version: v3.14
+
+      - name: Failure - it did not fail as expected
+        if: steps.install-package.outcome != 'failure'
+        run: |
+          echo "❌ Error: Step should have failed but didn't!"
+          exit 1
+
+      - name: Success - it failed as expected
+        if: steps.install-package.outcome == 'failure'
+        run: echo "✅ Test passed - step failed as expected"
